from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io


def generate_portfolio_pdf(student: dict, profile: dict, submissions: list) -> bytes:
    """Generate a PDF portfolio for a student and return as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title style
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a2e"),
        alignment=TA_CENTER,
        spaceAfter=6,
    )

    # Subtitle style
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.HexColor("#4a4a6a"),
        alignment=TA_CENTER,
        spaceAfter=4,
    )

    # Section heading style
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=16,
        spaceAfter=8,
    )

    # Normal text style
    normal_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#374151"),
        spaceAfter=4,
    )

    # Header
    elements.append(Paragraph("Pragati", title_style))
    elements.append(Paragraph("Student Activity Portfolio", subtitle_style))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a1a2e")))
    elements.append(Spacer(1, 0.2 * inch))

    # Student info
    elements.append(Paragraph("Student Information", section_style))
    student_data = [
        ["Full Name", student.get("full_name", "")],
        ["Email", student.get("email", "")],
        ["Institution", student.get("institution", "N/A")],
        ["Department", student.get("department", "N/A")],
    ]
    student_table = Table(student_data, colWidths=[2 * inch, 4.5 * inch])
    student_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f3f4f6")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1a1a2e")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
    ]))
    elements.append(student_table)
    elements.append(Spacer(1, 0.2 * inch))

    # Verified activities
    elements.append(Paragraph("Verified Activities", section_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb")))
    elements.append(Spacer(1, 0.1 * inch))

    if not submissions:
        elements.append(Paragraph("No verified activities found.", normal_style))
    else:
        table_data = [["#", "Title", "Category", "Status", "Date"]]
        for i, s in enumerate(submissions, 1):
            table_data.append([
                str(i),
                s.get("title", ""),
                str(s.get("category", "")).capitalize(),
                str(s.get("status", "")).capitalize(),
                str(s.get("created_at", ""))[:10],
            ])

        act_table = Table(table_data, colWidths=[0.3 * inch, 2.5 * inch, 1.2 * inch, 1 * inch, 1.2 * inch])
        act_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
            ("ROWBACKGROUNDS", (1, 0), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ]))
        elements.append(act_table)

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb")))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(
        "This document is auto-generated by Pragati — Centralised Student Activity Record Platform.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                        textColor=colors.HexColor("#9ca3af"), alignment=TA_CENTER)
    ))

    doc.build(elements)
    return buffer.getvalue()